### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by hashanmalawana** [digitoimistodude/air#18]
Should be more clear and efficient for the users..Let's make more attractive interface

**Comment by timiwahalahti** [comment]
Can you elaborate this more, what do you mean specifically?

Please not that `*.css` files are not meant to be clear or easily human readable. Air uses SASS and Gulp to combine all sass-files to css-files.

**Comment by hashanmalawana** [comment]
We can design this more user friendly.Anyway This is much good..

**Comment by timiwahalahti** [comment]
Air is meant to be minimal starting point and developer friendly theme with tools that makes developing with it much nicer. Not that end-user friendly, as Air does not have that rich styles on front-end for example. It works and looks good, but is really really simplified for a reason.

We're happy to review PR's and have an explained ideas in issues :)
