### ISSUE TITLE
Container does not get height when placing divs inside of it and using Jeet grid

### ISSUE THREAD

**Issue by svirmasalo** [digitoimistodude/air#2]
If I put divs inside of an container element, and assign them with Jeet markup col(x/y), the container will be height of 0(+paddings). If I simply give container a float:left, then the height kicks in, but centering wont work. 

Here's my html and css

**HTML**
```
<section id="smthn">
  <div class="container">
    <div class="nut">/*Lot of stuff inside*/</div>
    <div class="nut">/*Lot of stuff inside*/</div>
    <div class="nut">/*Lot of stuff inside*/</div>
  </div>
</section>
```

**SCSS**
```
#smthn{
 @include col(1);
 .container{
  @include center($grid-base-size);
   .nut{
    @include col(1/3, $cycle:3);
   }
  }
 }
}
```

Any ideas? Jeet is pretty new to me, so am I missing something here?

**Comment by ronilaukkarinen** [comment]
This is more of a [jeet](https://github.com/mojotech/jeet) issue, but you always need `overflow: hidden;` in container for it to act properly. Also, no `@include col(1);` needed if you only have one full width column.
